[linux_fleet]
YOUR_SERVER1_IP ansible_user=ansible_svc
YOUR_SERVER2_IP ansible_user=ansible_svc

[linux_fleet:vars]
ansible_user=ansible_svc

[new_linux_servers]
#When you get a new server
#IP_new_linux_server ansible_user=linux_user ansible_password=YourPasswordHere ansible_become_password=YourPasswordHere

# OR
#only the SERVER_IP
#Run the Bootstrap with the Vault Key
#ansible-playbook -i inventories/hosts.ini scripts/bootstrap.yml --ask-vault-pass

#Once the bootstrap is finished and the new 
#linux server has the ansible_svc user and 
#SSH keys, you should move the IP in your 
#hosts.ini from [new_linux_servers] 
#to [linux_fleet].
